"""Initial Schema

Revision ID: ed713aa8523a
Revises: 
Create Date: 2026-04-07 23:09:26.735516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed713aa8523a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_table('calendar',
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calendar_name', sa.String(length=255), nullable=False),
    sa.Column('calendar_provider_id', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('calendar_id')
    )
    op.create_index(op.f('ix_calendar_calendar_id'), 'calendar', ['calendar_id'], unique=False)
    op.create_index(op.f('ix_calendar_user_id'), 'calendar', ['user_id'], unique=False)
    op.create_table('connected_account',
    sa.Column('connected_account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('account_email', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('connected_account_id')
    )
    op.create_index(op.f('ix_connected_account_connected_account_id'), 'connected_account', ['connected_account_id'], unique=False)
    op.create_index(op.f('ix_connected_account_user_id'), 'connected_account', ['user_id'], unique=False)
    op.create_table('workspace',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='workspacestatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_index(op.f('ix_workspace_owner_user_id'), 'workspace', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_workspace_workspace_id'), 'workspace', ['workspace_id'], unique=False)
    op.create_table('assistant_session',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'FAILED', 'CANCELLED', name='sessionstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_assistant_session_session_id'), 'assistant_session', ['session_id'], unique=False)
    op.create_index(op.f('ix_assistant_session_user_id'), 'assistant_session', ['user_id'], unique=False)
    op.create_index(op.f('ix_assistant_session_workspace_id'), 'assistant_session', ['workspace_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'READ', 'EXECUTE', name='auditaction'), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_audit_log_audit_id'), 'audit_log', ['audit_id'], unique=False)
    op.create_index(op.f('ix_audit_log_workspace_id'), 'audit_log', ['workspace_id'], unique=False)
    op.create_table('integration',
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('service_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ),
    sa.PrimaryKeyConstraint('integration_id')
    )
    op.create_index(op.f('ix_integration_integration_id'), 'integration', ['integration_id'], unique=False)
    op.create_index(op.f('ix_integration_workspace_id'), 'integration', ['workspace_id'], unique=False)
    op.create_table('oauth_token',
    sa.Column('oauth_token_id', sa.Integer(), nullable=False),
    sa.Column('connected_account_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_type', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connected_account_id'], ['connected_account.connected_account_id'], ),
    sa.PrimaryKeyConstraint('oauth_token_id')
    )
    op.create_index(op.f('ix_oauth_token_connected_account_id'), 'oauth_token', ['connected_account_id'], unique=False)
    op.create_index(op.f('ix_oauth_token_oauth_token_id'), 'oauth_token', ['oauth_token_id'], unique=False)
    op.create_table('sheet',
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.String(length=255), nullable=False),
    sa.Column('sheet_provider_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ),
    sa.PrimaryKeyConstraint('sheet_id')
    )
    op.create_index(op.f('ix_sheet_sheet_id'), 'sheet', ['sheet_id'], unique=False)
    op.create_index(op.f('ix_sheet_workspace_id'), 'sheet', ['workspace_id'], unique=False)
    op.create_table('message',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['assistant_session.session_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_message_message_id'), 'message', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_session_id'), 'message', ['session_id'], unique=False)
    op.create_table('token_usage',
    sa.Column('usage_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('usage_type', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['assistant_session.session_id'], ),
    sa.PrimaryKeyConstraint('usage_id')
    )
    op.create_index(op.f('ix_token_usage_session_id'), 'token_usage', ['session_id'], unique=False)
    op.create_index(op.f('ix_token_usage_usage_id'), 'token_usage', ['usage_id'], unique=False)
    op.create_table('tool_call',
    sa.Column('tool_call_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='toolcallstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['assistant_session.session_id'], ),
    sa.PrimaryKeyConstraint('tool_call_id')
    )
    op.create_index(op.f('ix_tool_call_session_id'), 'tool_call', ['session_id'], unique=False)
    op.create_index(op.f('ix_tool_call_tool_call_id'), 'tool_call', ['tool_call_id'], unique=False)
    op.create_table('tool_result',
    sa.Column('tool_result_id', sa.Integer(), nullable=False),
    sa.Column('tool_call_id', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tool_call_id'], ['tool_call.tool_call_id'], ),
    sa.PrimaryKeyConstraint('tool_result_id')
    )
    op.create_index(op.f('ix_tool_result_tool_call_id'), 'tool_result', ['tool_call_id'], unique=False)
    op.create_index(op.f('ix_tool_result_tool_result_id'), 'tool_result', ['tool_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_result_tool_result_id'), table_name='tool_result')
    op.drop_index(op.f('ix_tool_result_tool_call_id'), table_name='tool_result')
    op.drop_table('tool_result')
    op.drop_index(op.f('ix_tool_call_tool_call_id'), table_name='tool_call')
    op.drop_index(op.f('ix_tool_call_session_id'), table_name='tool_call')
    op.drop_table('tool_call')
    op.drop_index(op.f('ix_token_usage_usage_id'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_session_id'), table_name='token_usage')
    op.drop_table('token_usage')
    op.drop_index(op.f('ix_message_session_id'), table_name='message')
    op.drop_index(op.f('ix_message_message_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_sheet_workspace_id'), table_name='sheet')
    op.drop_index(op.f('ix_sheet_sheet_id'), table_name='sheet')
    op.drop_table('sheet')
    op.drop_index(op.f('ix_oauth_token_oauth_token_id'), table_name='oauth_token')
    op.drop_index(op.f('ix_oauth_token_connected_account_id'), table_name='oauth_token')
    op.drop_table('oauth_token')
    op.drop_index(op.f('ix_integration_workspace_id'), table_name='integration')
    op.drop_index(op.f('ix_integration_integration_id'), table_name='integration')
    op.drop_table('integration')
    op.drop_index(op.f('ix_audit_log_workspace_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_audit_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_assistant_session_workspace_id'), table_name='assistant_session')
    op.drop_index(op.f('ix_assistant_session_user_id'), table_name='assistant_session')
    op.drop_index(op.f('ix_assistant_session_session_id'), table_name='assistant_session')
    op.drop_table('assistant_session')
    op.drop_index(op.f('ix_workspace_workspace_id'), table_name='workspace')
    op.drop_index(op.f('ix_workspace_owner_user_id'), table_name='workspace')
    op.drop_table('workspace')
    op.drop_index(op.f('ix_connected_account_user_id'), table_name='connected_account')
    op.drop_index(op.f('ix_connected_account_connected_account_id'), table_name='connected_account')
    op.drop_table('connected_account')
    op.drop_index(op.f('ix_calendar_user_id'), table_name='calendar')
    op.drop_index(op.f('ix_calendar_calendar_id'), table_name='calendar')
    op.drop_table('calendar')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
